avatar_5a584c8b-512f-4f70-848c-a3d1efbb988f_1782690149:
  preparation: False
  bbox_shift: 0
  video_path: "uploads/videos/avatar_5a584c8b-512f-4f70-848c-a3d1efbb988f_1782690149_talking_tmpaqvjuogs.mp4"
  audio_clips:
    landing_sample_eng_60s: "data/audio/eng.wav"
