#!/usr/bin/env bash
# Shared env layering helpers for the MuseTalk launch chain (startup rework 2026-09-28).
#
# Sourced by scripts/run_musetalk_server.sh, scripts/run_webrtc_relay_api_server.sh,
# scripts/vast_server_ctl.sh and scripts/vast_onstart.sh. See docs/STARTUP.md.
#
# Effective value of any knob, highest wins:
#   1. the caller's environment (explicit export, Vast template env, TURN env file sourced by ctl)
#   2. operator overrides files: MUSETALK_ENV_OVERRIDES_FILE (colon-separated list; default
#      <repo>/.runtime/musetalk_overrides.env; missing files are skipped), earlier files win
#   3. <repo>/.runtime/musetalk_resolved.env, regenerated by scripts/musetalk_host_profile.py
#   4. code defaults
#
# Env files are PARSED, never sourced or eval'd: `KEY=VALUE` / `export KEY=VALUE` lines,
# blank lines and `#` comments ignored, values may be 'single-quoted' (with the '\'' idiom),
# "double-quoted" (no expansion) or bare (an inline ` # comment` after whitespace is allowed).
# `$`, backticks and shell metacharacters outside single quotes are rejected, so a file can
# never run code. A key is exported only while it is still UNSET ([[ -z "${!key+x}" ]]).

if [[ -n "${MT_ENV_LAYERS_LOADED:-}" ]]; then
  return 0
fi
MT_ENV_LAYERS_LOADED=1

declare -gA MT_ENV_SOURCE=()        # key -> caller | overrides:<file> | resolved:<file> | launcher:<why>
declare -ga MT_ENV_FILES_USED=()    # overrides files that existed and were read
declare -ga MT_ENV_OVERRIDES_FILES=()
declare -ga MT_ENV_WARNINGS=()
MT_ENV_LOG_PREFIX="${MT_ENV_LOG_PREFIX:-musetalk_env}"
MT_ENV_PARSED=""
MT_ENV_ERROR=""
MT_ENV_KEY=""
MT_ENV_VALUE=""
MT_ENV_LAST_LOADED=0
MT_ENV_LAST_KEPT=0
MT_ENV_LAST_INVALID=0
MT_ENV_PEEK_SOURCE=""
MT_ENV_PEEK_VALUE=""
MT_ENV_RECIPE="fast"
MT_ENV_RECIPE_SOURCE="default"

# Keys an env file may never set (shell/loader behaviour, not MuseTalk levers).
MT_ENV_DENY_RE='^(BASH_ENV|ENV|IFS|SHELLOPTS|BASHOPTS|PS4|PROMPT_COMMAND|MT_ENV_[A-Z0-9_]*)$'
# Values of keys matching this are never printed.
MT_ENV_SECRET_RE='(^|_)(KEY|SECRET|TOKEN|PASS|PASSWORD|PASSWD|CREDENTIAL|CREDENTIALS|AUTH|PRIVATE)(_|$)'

# Pass-through 300 fps / serving levers. The launch chain never sets these itself (the
# resolver may emit some for recipe fast300); they are listed so --print-env, the launch
# summary and .runtime/musetalk_launch_<port>.json report their effective value + source.
MT_PASSTHROUGH_LEVERS=(
  # engines
  MUSETALK_TAESD_BACKEND MUSETALK_TAESD_TRT_DIR MUSETALK_TAESD_TRT_BATCH MUSETALK_TAESD_TRT_BUILD
  MUSETALK_TAESD_TRT_STRICT MUSETALK_TAESD_TRT_FUSED_POST MUSETALK_TAESD_TRT_OPT_LEVEL
  MUSETALK_TAESD_TRT_STRONGLY_TYPED MUSETALK_UNET_STAGEWISE_BATCH MUSETALK_UNET_STAGEWISE_CACHE_DIR
  MUSETALK_UNET_STAGEWISE_CUDAGRAPH MUSETALK_UNET_STAGEWISE_PROBE_CHECK MUSETALK_UNET_STAGEWISE_PROBE_TOL
  MUSETALK_UNET_STAGEWISE_VERIFY_SHA MUSETALK_TRT_UNET_CUDAGRAPHS MUSETALK_FREE_EAGER_UNET
  # serving
  WEBRTC_NONBLOCKING_HANDOFF WEBRTC_HANDOFF_MAX_PENDING_FRAMES WEBRTC_HANDOFF_CONVERT_THREADS
  WEBRTC_YUV_IN_COMPOSE WEBRTC_IDLE_FRAME_CACHE WEBRTC_IDLE_FRAME_CACHE_MAX_MB
  WEBRTC_IDLE_FRAME_CACHE_DECODE_THREADS WEBRTC_IDLE_FRAME_CACHE_WORKERS HLS_GPU_PIPELINE_DEPTH
  HLS_GPU_OUTPUT_RING HLS_GPU_BLOCKING_WAIT HLS_SCHEDULER_POLICY HLS_SCHEDULER_MAX_RUNAHEAD_S
  HLS_SCHEDULER_EDF_STARTUP_FRAMES HLS_SCHEDULER_EDF_URGENT_S HLS_SCHEDULER_EDF_MAX_QUEUE_FRAMES
  HLS_SKIP_GPU_FOR_RAW HLS_SKIP_RAW_MAX_PENDING_BATCHES HLS_SKIP_CROSSFADE_COPY MUSETALK_WHISPER_STREAM
  WEBRTC_RAW_IDLE_POSE WEBRTC_GROUP_MAX_COUNT MUSETALK_DISABLE_LOCAL_TTS MUSETALK_THREAD_CAPS
  MUSETALK_IDLE_DECODE_THREADS MUSETALK_MOTION_DECODE_THREADS MUSETALK_TORCH_INTRAOP_THREADS
  MUSETALK_CV2_THREADS MUSETALK_FFMPEG_EXECUTOR_WORKERS HLS_GPU_STAGE_SYNC_TIMING
  MUSETALK_VAE_DECODE_TIMING_SYNC MALLOC_ARENA_MAX
  # memory
  MUSETALK_AVATAR_MASK_CHANNELS MUSETALK_AVATAR_MASK_STORE MUSETALK_AVATAR_FRAME_STORE
  MUSETALK_AVATAR_DECODED_LRU_FRAMES MUSETALK_AVATAR_PNG_READAHEAD MUSETALK_AVATAR_PNG_DECODE_WORKERS
  MUSETALK_AVATAR_PLAN_FLOAT_ALPHA MUSETALK_AVATAR_DEDUP_CYCLE
  # encoders
  WEBRTC_VP8_ENCODER WEBRTC_NATIVE_VP8_DIR WEBRTC_NATIVE_VP8_THREADS WEBRTC_NATIVE_VP8_MAX_BITRATE_BPS
  WEBRTC_NATIVE_VP8_BITRATE_FLOOR_BPS WEBRTC_H264_IMPL WEBRTC_H264_X264_PRESET WEBRTC_H264_X264_THREADS
  WEBRTC_H264_NVENC_PRESET WEBRTC_H264_NVENC_TUNE WEBRTC_NVENC_MAX_SESSIONS WEBRTC_H264_MAXBITRATE
  # telemetry
  WEBRTC_LIFETIME_COUNTERS WEBRTC_LIFETIME_SEND_RING HLS_GPU_EVENT_TIMING HLS_GPU_TIMING_WINDOW
  WEBRTC_HANDOFF_VERIFY WEBRTC_PREENCODE_SHA_DIR WEBRTC_H264_ENCODE_TIMING MUSETALK_VAE_DECODE_TIMING
  SERVER_RESOURCE_LOG_INTERVAL
  # tools
  MUSETALK_CHIN_TRACKER_PYTHON
)

# Launch-control knobs that scripts before the launcher (vast_onstart.sh, vast_server_ctl.sh)
# also honour from the overrides files, via mt_env_peek.
MT_LAUNCH_CONTROL_KNOBS=(
  MUSETALK_RECIPE MUSETALK_UNET_MODE MUSETALK_VERIFY_RECIPE MUSETALK_UNET_ENGINE_PROVISION
  MUSETALK_TAESD_TRT_PROVISION MUSETALK_UNET_STAGEWISE_PROVISION MUSETALK_VP8_FALLBACK
)

mt_env_log() {
  printf '[%s] %s\n' "$MT_ENV_LOG_PREFIX" "$*" >&2
}

mt_env_warn() {
  MT_ENV_WARNINGS+=("$*")
  printf '[%s] WARNING: %s\n' "$MT_ENV_LOG_PREFIX" "$*" >&2
}

mt_env_is_true() {
  case "${1:-}" in
    1|true|TRUE|True|yes|YES|Yes|on|ON|On)
      return 0
      ;;
  esac
  return 1
}

mt_env_lower() {
  printf '%s' "${1,,}"
}

mt_env_is_secret_key() {
  [[ "${1^^}" =~ $MT_ENV_SECRET_RE ]]
}

# Single-quote a value for a shell-sourceable line.
mt_env_quote() {
  local _mt_v="$1"
  printf "'%s'" "${_mt_v//\'/\'\\\'\'}"
}

# Value for logs/print-env: secrets are redacted.
mt_env_display() {
  local _mt_key="$1" _mt_value="$2"
  if mt_env_is_secret_key "$_mt_key"; then
    if [[ -n "$_mt_value" ]]; then
      printf '<redacted>'
    else
      printf "''"
    fi
    return 0
  fi
  mt_env_quote "$_mt_value"
}

# mt_env_parse_value RAW -> MT_ENV_PARSED (return 1 and MT_ENV_ERROR on a syntax error).
mt_env_parse_value() {
  local _mt_raw="$1" _mt_out="" _mt_c _mt_rest _mt_seg _mt_next _mt_closed
  local -i _mt_i=0 _mt_n
  MT_ENV_PARSED=""
  MT_ENV_ERROR=""
  _mt_raw="${_mt_raw%$'\r'}"
  _mt_raw="${_mt_raw%"${_mt_raw##*[![:space:]]}"}"
  _mt_n=${#_mt_raw}
  while (( _mt_i < _mt_n )); do
    _mt_c="${_mt_raw:_mt_i:1}"
    case "$_mt_c" in
      "'")
        _mt_rest="${_mt_raw:_mt_i+1}"
        if [[ "$_mt_rest" != *"'"* ]]; then
          MT_ENV_ERROR="unterminated single quote"
          return 1
        fi
        _mt_seg="${_mt_rest%%\'*}"
        _mt_out+="$_mt_seg"
        _mt_i=$(( _mt_i + ${#_mt_seg} + 2 ))
        ;;
      '"')
        _mt_i=$(( _mt_i + 1 ))
        _mt_closed=0
        while (( _mt_i < _mt_n )); do
          _mt_c="${_mt_raw:_mt_i:1}"
          if [[ "$_mt_c" == '"' ]]; then
            _mt_closed=1
            _mt_i=$(( _mt_i + 1 ))
            break
          elif [[ "$_mt_c" == '\' ]]; then
            _mt_next="${_mt_raw:_mt_i+1:1}"
            case "$_mt_next" in
              '"'|'\'|'$'|'`')
                _mt_out+="$_mt_next"
                _mt_i=$(( _mt_i + 2 ))
                ;;
              *)
                _mt_out+="$_mt_c"
                _mt_i=$(( _mt_i + 1 ))
                ;;
            esac
          elif [[ "$_mt_c" == '$' || "$_mt_c" == '`' ]]; then
            MT_ENV_ERROR='expansion ($ or backtick) is not supported; single-quote the value'
            return 1
          else
            _mt_out+="$_mt_c"
            _mt_i=$(( _mt_i + 1 ))
          fi
        done
        if (( ! _mt_closed )); then
          MT_ENV_ERROR="unterminated double quote"
          return 1
        fi
        ;;
      '\')
        if (( _mt_i + 1 >= _mt_n )); then
          MT_ENV_ERROR="trailing backslash"
          return 1
        fi
        _mt_out+="${_mt_raw:_mt_i+1:1}"
        _mt_i=$(( _mt_i + 2 ))
        ;;
      ' '|$'\t')
        _mt_rest="${_mt_raw:_mt_i}"
        _mt_rest="${_mt_rest#"${_mt_rest%%[![:space:]]*}"}"
        if [[ -z "$_mt_rest" || "$_mt_rest" == \#* ]]; then
          break
        fi
        MT_ENV_ERROR="unquoted whitespace in value; quote it"
        return 1
        ;;
      '$'|'`')
        MT_ENV_ERROR='expansion ($ or backtick) is not supported; single-quote the value'
        return 1
        ;;
      ';'|'|'|'&'|'<'|'>'|'('|')')
        MT_ENV_ERROR="unquoted shell metacharacter '$_mt_c'; quote the value"
        return 1
        ;;
      *)
        _mt_out+="$_mt_c"
        _mt_i=$(( _mt_i + 1 ))
        ;;
    esac
  done
  MT_ENV_PARSED="$_mt_out"
  return 0
}

# mt_env_parse_line LINE -> 0 assignment (MT_ENV_KEY/MT_ENV_VALUE), 1 blank/comment, 2 invalid.
mt_env_parse_line() {
  local _mt_line="${1%$'\r'}" _mt_key _mt_raw
  _mt_line="${_mt_line#"${_mt_line%%[![:space:]]*}"}"
  if [[ -z "$_mt_line" || "$_mt_line" == \#* ]]; then
    return 1
  fi
  if [[ "$_mt_line" =~ ^export[[:space:]]+ ]]; then
    _mt_line="${_mt_line#export}"
    _mt_line="${_mt_line#"${_mt_line%%[![:space:]]*}"}"
  fi
  if [[ "$_mt_line" != *=* ]]; then
    MT_ENV_ERROR="not a KEY=VALUE line"
    return 2
  fi
  _mt_key="${_mt_line%%=*}"
  _mt_raw="${_mt_line#*=}"
  if ! [[ "$_mt_key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
    MT_ENV_ERROR="invalid variable name '${_mt_key}'"
    return 2
  fi
  if [[ "$_mt_key" =~ $MT_ENV_DENY_RE ]]; then
    MT_ENV_ERROR="variable '${_mt_key}' may not be set from an env file"
    return 2
  fi
  if ! mt_env_parse_value "$_mt_raw"; then
    return 2
  fi
  MT_ENV_KEY="$_mt_key"
  MT_ENV_VALUE="$MT_ENV_PARSED"
  return 0
}

# Record every variable already exported as coming from the caller.
mt_env_record_caller() {
  local _mt_name
  while IFS= read -r _mt_name; do
    [[ -n "$_mt_name" ]] || continue
    if [[ -z "${MT_ENV_SOURCE[$_mt_name]:-}" ]]; then
      MT_ENV_SOURCE[$_mt_name]="caller"
    fi
  done < <(compgen -e)
}

# mt_env_load_file FILE LABEL: export each assignment only while the key is still unset.
mt_env_load_file() {
  local _mt_file="$1" _mt_label="${2:-$1}" _mt_line _mt_rc
  local -i _mt_lineno=0
  MT_ENV_LAST_LOADED=0
  MT_ENV_LAST_KEPT=0
  MT_ENV_LAST_INVALID=0
  if [[ ! -e "$_mt_file" ]]; then
    return 0
  fi
  if [[ ! -f "$_mt_file" || ! -r "$_mt_file" ]]; then
    mt_env_warn "cannot read env file $_mt_file; skipped"
    return 0
  fi
  while IFS= read -r _mt_line || [[ -n "$_mt_line" ]]; do
    _mt_lineno=$(( _mt_lineno + 1 ))
    _mt_rc=0
    mt_env_parse_line "$_mt_line" || _mt_rc=$?
    case "$_mt_rc" in
      0)
        if [[ -z "${!MT_ENV_KEY+x}" ]]; then
          export "$MT_ENV_KEY=$MT_ENV_VALUE"
          MT_ENV_SOURCE[$MT_ENV_KEY]="$_mt_label"
          MT_ENV_LAST_LOADED=$(( MT_ENV_LAST_LOADED + 1 ))
        else
          MT_ENV_LAST_KEPT=$(( MT_ENV_LAST_KEPT + 1 ))
        fi
        ;;
      1)
        ;;
      *)
        MT_ENV_LAST_INVALID=$(( MT_ENV_LAST_INVALID + 1 ))
        mt_env_warn "$_mt_file:$_mt_lineno ignored: $MT_ENV_ERROR"
        ;;
    esac
  done < "$_mt_file"
  return 0
}

# mt_env_file_get FILE KEY: print the FIRST value FILE assigns to KEY (what loading would export).
mt_env_file_get() {
  local _mt_file="$1" _mt_want="$2" _mt_line _mt_rc
  [[ -f "$_mt_file" && -r "$_mt_file" ]] || return 1
  while IFS= read -r _mt_line || [[ -n "$_mt_line" ]]; do
    _mt_rc=0
    mt_env_parse_line "$_mt_line" || _mt_rc=$?
    if (( _mt_rc == 0 )) && [[ "$MT_ENV_KEY" == "$_mt_want" ]]; then
      printf '%s' "$MT_ENV_VALUE"
      return 0
    fi
  done < "$_mt_file"
  return 1
}

# mt_env_file_keys FILE: print each assigned key once (file order).
mt_env_file_keys() {
  local _mt_file="$1" _mt_line _mt_rc
  local -A _mt_seen=()
  [[ -f "$_mt_file" && -r "$_mt_file" ]] || return 0
  while IFS= read -r _mt_line || [[ -n "$_mt_line" ]]; do
    _mt_rc=0
    mt_env_parse_line "$_mt_line" || _mt_rc=$?
    if (( _mt_rc == 0 )) && [[ -z "${_mt_seen[$MT_ENV_KEY]:-}" ]]; then
      _mt_seen[$MT_ENV_KEY]=1
      printf '%s\n' "$MT_ENV_KEY"
    fi
  done < "$_mt_file"
}

# mt_env_overrides_list REPO_ROOT -> MT_ENV_OVERRIDES_FILES (configured order; may not exist).
mt_env_overrides_list() {
  local _mt_repo="$1" _mt_spec _mt_item
  local _mt_default="${MUSETALK_RUNTIME_DIR:-$_mt_repo/.runtime}/musetalk_overrides.env"
  local -a _mt_items=()
  MT_ENV_OVERRIDES_FILES=()
  if [[ -n "${MUSETALK_ENV_OVERRIDES_FILE+x}" ]]; then
    _mt_spec="$MUSETALK_ENV_OVERRIDES_FILE"
  else
    _mt_spec="$_mt_default"
  fi
  IFS=':' read -r -a _mt_items <<< "$_mt_spec" || true
  for _mt_item in "${_mt_items[@]}"; do
    [[ -n "$_mt_item" ]] || continue
    if [[ "$_mt_item" != /* ]]; then
      _mt_item="$_mt_repo/$_mt_item"
    fi
    MT_ENV_OVERRIDES_FILES+=("$_mt_item")
  done
}

# mt_env_load_overrides REPO_ROOT: layer 2, earlier files win, missing files skipped.
mt_env_load_overrides() {
  local _mt_file
  mt_env_overrides_list "$1"
  MT_ENV_FILES_USED=()
  for _mt_file in "${MT_ENV_OVERRIDES_FILES[@]}"; do
    if [[ ! -e "$_mt_file" ]]; then
      continue
    fi
    mt_env_load_file "$_mt_file" "overrides:$_mt_file"
    MT_ENV_FILES_USED+=("$_mt_file")
    mt_env_log "overrides $_mt_file: exported=$MT_ENV_LAST_LOADED kept_higher_layer=$MT_ENV_LAST_KEPT invalid=$MT_ENV_LAST_INVALID"
  done
}

# mt_env_peek KEY REPO_ROOT: the value KEY will have after layer 2 (caller env, else the first
# overrides file that assigns it) WITHOUT exporting anything. Sets MT_ENV_PEEK_VALUE and
# MT_ENV_PEEK_SOURCE; returns 1 (both empty) when neither layer sets KEY. Prints nothing.
mt_env_peek() {
  local _mt_key="$1" _mt_repo="$2" _mt_file _mt_value
  MT_ENV_PEEK_VALUE=""
  MT_ENV_PEEK_SOURCE=""
  if [[ -n "${!_mt_key+x}" ]]; then
    MT_ENV_PEEK_VALUE="${!_mt_key}"
    MT_ENV_PEEK_SOURCE="${MT_ENV_SOURCE[$_mt_key]:-caller}"
    return 0
  fi
  mt_env_overrides_list "$_mt_repo"
  for _mt_file in "${MT_ENV_OVERRIDES_FILES[@]}"; do
    if _mt_value="$(mt_env_file_get "$_mt_file" "$_mt_key")"; then
      MT_ENV_PEEK_VALUE="$_mt_value"
      MT_ENV_PEEK_SOURCE="overrides:$_mt_file"
      return 0
    fi
  done
  return 1
}

# mt_env_peek_or KEY REPO_ROOT DEFAULT: print the peeked value, or DEFAULT.
mt_env_peek_or() {
  if mt_env_peek "$1" "$2"; then
    printf '%s' "$MT_ENV_PEEK_VALUE"
  else
    printf '%s' "${3:-}"
  fi
}

# mt_env_effective_recipe REPO_ROOT -> MT_ENV_RECIPE (fast default | fast300 | legacy_int8 |
# anything else, left for the caller to reject) and MT_ENV_RECIPE_SOURCE. Prints nothing.
mt_env_effective_recipe() {
  local _mt_value=""
  MT_ENV_RECIPE_SOURCE="default"
  if mt_env_peek MUSETALK_RECIPE "$1"; then
    _mt_value="$MT_ENV_PEEK_VALUE"
    MT_ENV_RECIPE_SOURCE="$MT_ENV_PEEK_SOURCE"
  fi
  _mt_value="${_mt_value,,}"
  _mt_value="${_mt_value//[[:space:]]/}"
  case "$_mt_value" in
    ""|default)
      MT_ENV_RECIPE="fast"
      ;;
    legacy|int8|legacy-int8)
      MT_ENV_RECIPE="legacy_int8"
      ;;
    *)
      MT_ENV_RECIPE="$_mt_value"
      ;;
  esac
}
