#!/usr/bin/env python3
"""Fetch MuseTalk worker runtime secrets and write shell exports.

The script intentionally logs only secret names and environment variable names,
never values. The generated file is meant to be sourced by Vast on-start and
deleted immediately after sourcing.
"""

import argparse
import base64
import json
import os
import re
import shlex
import stat
from pathlib import Path
from typing import Any

import boto3
from botocore.config import Config


DEFAULT_REGION = "us-east-1"
ENV_NAME_RE = re.compile(r"^[A-Z_][A-Z0-9_]*$")
DEFAULT_S3_BUCKET_ENV_NAMES = (
    "AVATAR_S3_BUCKET",
    "TTS_AUDIO_BUCKET",
    "IDLE_VIDEO_BUCKET",
    "UPLOAD_BUCKETS",
)
SECRET_ID_ENV = "MUSETALK_AWS_SECRET_ID"


def _env_flag(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _resolve_secret_region() -> str:
    return (
        os.getenv("MUSETALK_AWS_SECRET_REGION", "").strip()
        or os.getenv("AWS_SECRETS_REGION", "").strip()
        or os.getenv("AWS_DEFAULT_REGION", "").strip()
        or os.getenv("AWS_REGION", "").strip()
        or DEFAULT_REGION
    )


def _read_secret_payload(secret_id: str, region: str) -> dict[str, Any]:
    client = boto3.client(
        "secretsmanager",
        region_name=region,
        config=Config(
            connect_timeout=5,
            read_timeout=15,
            retries={"max_attempts": 3, "mode": "standard"},
        ),
    )
    response = client.get_secret_value(SecretId=secret_id)

    if "SecretString" in response:
        raw_secret = response["SecretString"]
    else:
        raw_secret = base64.b64decode(response["SecretBinary"]).decode("utf-8")

    payload = json.loads(raw_secret)
    if not isinstance(payload, dict):
        raise ValueError("Secrets Manager payload must be a JSON object")
    return payload


def _stringify_secret_value(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float, str)):
        return str(value)
    return json.dumps(value, separators=(",", ":"))


def _exports_from_payload(payload: dict[str, Any]) -> dict[str, str]:
    exports: dict[str, str] = {}
    skipped: list[str] = []

    for key, value in payload.items():
        env_name = str(key).strip()
        if not ENV_NAME_RE.fullmatch(env_name):
            skipped.append(env_name)
            continue

        env_value = _stringify_secret_value(value)
        if env_value is None:
            continue
        exports[env_name] = env_value

    if "AWS_REGION" not in exports and exports.get("AWS_DEFAULT_REGION"):
        exports["AWS_REGION"] = exports["AWS_DEFAULT_REGION"]
    if "AWS_DEFAULT_REGION" not in exports and exports.get("AWS_REGION"):
        exports["AWS_DEFAULT_REGION"] = exports["AWS_REGION"]
    if "AVATAR_S3_REGION" not in exports:
        region = exports.get("AWS_REGION") or exports.get("AWS_DEFAULT_REGION")
        if region:
            exports["AVATAR_S3_REGION"] = region
    if "AVATAR_S3_BUCKET" not in exports and exports.get("MUSETALK_AVATAR_S3_BUCKET"):
        exports["AVATAR_S3_BUCKET"] = exports["MUSETALK_AVATAR_S3_BUCKET"]
    if "AVATAR_S3_ENABLED" not in exports and exports.get("AVATAR_S3_BUCKET"):
        exports["AVATAR_S3_ENABLED"] = "1"

    if skipped:
        print(
            "Skipped secret keys with invalid env-var names: "
            + ", ".join(sorted(skipped))
        )

    return exports


def _write_export_file(path: Path, exports: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(
        path,
        os.O_WRONLY | os.O_CREAT | os.O_TRUNC,
        stat.S_IRUSR | stat.S_IWUSR,
    )
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write("# Generated by scripts/bootstrap_aws_secrets.py\n")
        handle.write("# Values intentionally omitted from logs; delete after sourcing.\n")
        for key in sorted(exports):
            handle.write(f"export {key}={shlex.quote(exports[key])}\n")
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)


def _runtime_env_with_exports(exports: dict[str, str]) -> dict[str, str]:
    runtime_env = dict(os.environ)
    runtime_env.update(exports)
    return runtime_env


def _bucket_names_from_exports(exports: dict[str, str]) -> list[str]:
    buckets: list[str] = []
    for name in DEFAULT_S3_BUCKET_ENV_NAMES:
        raw_value = exports.get(name, "")
        for token in raw_value.split(","):
            bucket = token.strip()
            if bucket and bucket not in buckets:
                buckets.append(bucket)
    return buckets


def _verify_s3_buckets(exports: dict[str, str], region: str) -> None:
    buckets = _bucket_names_from_exports(exports)
    if not buckets:
        print("No S3 bucket env vars found in secret; skipping S3 head_bucket checks")
        return

    runtime_env = _runtime_env_with_exports(exports)
    access_key_id = runtime_env.get("AWS_ACCESS_KEY_ID")
    secret_access_key = runtime_env.get("AWS_SECRET_ACCESS_KEY")
    if not access_key_id or not secret_access_key:
        raise RuntimeError(
            "S3 verification requires AWS_ACCESS_KEY_ID and "
            "AWS_SECRET_ACCESS_KEY in the MuseTalk runtime secret"
        )

    client = boto3.client(
        "s3",
        region_name=(
            runtime_env.get("AVATAR_S3_REGION")
            or runtime_env.get("AWS_REGION")
            or runtime_env.get("AWS_DEFAULT_REGION")
            or region
        ),
        aws_access_key_id=access_key_id,
        aws_secret_access_key=secret_access_key,
        aws_session_token=runtime_env.get("AWS_SESSION_TOKEN"),
        config=Config(
            connect_timeout=5,
            read_timeout=10,
            retries={"max_attempts": 2, "mode": "standard"},
        ),
    )

    for bucket in buckets:
        client.head_bucket(Bucket=bucket)
        print(f"Verified S3 bucket access: s3://{bucket}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Load MuseTalk runtime env vars from AWS Secrets Manager."
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Path to write a temporary 0600 shell export file.",
    )
    parser.add_argument(
        "--verify-s3",
        action="store_true",
        help="Run head_bucket checks for bucket env vars from the secret.",
    )
    args = parser.parse_args()

    secret_id = os.getenv(SECRET_ID_ENV, "").strip()
    if not secret_id:
        raise SystemExit(f"{SECRET_ID_ENV} is required")

    region = _resolve_secret_region()
    print(f"Fetching MuseTalk runtime secret from Secrets Manager region={region}")
    payload = _read_secret_payload(secret_id, region)
    exports = _exports_from_payload(payload)
    if not exports:
        raise RuntimeError("Secret payload did not contain any exportable env vars")

    _write_export_file(args.output, exports)
    print(
        f"Wrote {len(exports)} env exports to {args.output} "
        f"(mode=0600): {', '.join(sorted(exports))}"
    )

    if _env_flag("MUSETALK_SECRETS_VERIFY_S3", False) or args.verify_s3:
        _verify_s3_buckets(exports, region)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
