#!/usr/bin/env python3
"""Select the fastest validated MuseTalk TRT profile available on disk."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


SAFE_FIVE_INT8_STAGES = (
    "decoder_pre,"
    "decoder_mid_block,"
    "decoder_up_block_0,"
    "decoder_up_block_1,"
    "decoder_up_block_2"
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text())
    except FileNotFoundError:
        return {}
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON at {path}: {exc}") from exc


def _artifact_valid(artifact_dir: Path) -> tuple[bool, str]:
    engine_path = artifact_dir / "unet_trt.ts"
    meta_path = artifact_dir / "unet_trt_meta.json"
    if not engine_path.exists():
        return False, f"missing {engine_path}"
    if not meta_path.exists():
        return False, f"missing {meta_path}"

    meta = _read_json(meta_path)
    validation = meta.get("validation")
    if not isinstance(validation, dict):
        return False, f"missing validation block in {meta_path}"
    if validation.get("passed") is not True:
        return False, f"validation did not pass in {meta_path}"
    return True, "validated"


def _shell_quote(value: str) -> str:
    if value == "":
        return "''"
    safe = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_./,:+-=")
    if all(ch in safe for ch in value):
        return value
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _write_env(path: Path, values: dict[str, str], notes: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        "# Generated by scripts/select_unet_trt_profile.py",
        f"# Generated at {stamp}",
        "# Do not edit by hand; rerun the selector after rebuilding TRT artifacts.",
    ]
    lines.extend(f"# {note}" for note in notes)
    lines.extend(f"{key}={_shell_quote(str(value))}" for key, value in values.items())
    path.write_text("\n".join(lines) + "\n")


def _base_profile() -> dict[str, str]:
    return {
        "MUSETALK_VAE_BACKEND": "trt_stagewise",
        "MUSETALK_TRT_STAGEWISE_PRECISION": "int8_mixed",
        "MUSETALK_TRT_STAGEWISE_INT8_FRONTEND": "onnx_qdq",
        "MUSETALK_TRT_STAGEWISE_INT8_STAGES": SAFE_FIVE_INT8_STAGES,
        "MUSETALK_TRT_STAGEWISE_INT8_CALIBRATION_DIR": "./calibration/vae_decoder",
        "MUSETALK_TRT_STAGEWISE_INT8_CALIBRATION_ALGO": "minmax",
        "MUSETALK_TRT_STAGEWISE_INT8_CACHE_DIR": "./models/tensorrt/stagewise_int8_onnx_qdq_cache",
        "MUSETALK_TRT_STAGEWISE_INT8_USE_CACHE": "1",
        "MUSETALK_TRT_STAGEWISE_INT8_REQUIRE_CALIBRATION_CACHE": "1",
        "MUSETALK_UNET_BACKEND": "trt",
        "MUSETALK_TRT_UNET_ENABLED": "1",
        "MUSETALK_TRT_FALLBACK": "0",
        "MUSETALK_UNET_CALIBRATION_CAPTURE": "0",
        "WEBRTC_BATCH_FRAME_CALLBACK": "1",
        "MUSETALK_BLEND_FIXED_POINT": "1",
        "MUSETALK_BLEND_SHRINK_MASK_BBOX": "1",
    }


def _relative(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)


def build_profile(args: argparse.Namespace) -> tuple[dict[str, str], list[str]]:
    root = args.repo_root.resolve()
    bs8_dir = (root / args.bs8_dir).resolve()
    bs16_dir = (root / args.bs16_dir).resolve()
    bs8_valid, bs8_reason = _artifact_valid(bs8_dir)
    bs16_valid, bs16_reason = _artifact_valid(bs16_dir)

    values = _base_profile()
    notes = [
        f"batch-8 artifact: {bs8_reason}",
        f"batch-16 artifact: {bs16_reason}",
    ]

    if args.prefer == "exact16" and bs16_valid:
        values.update(
            {
                "MUSETALK_TRT_PROFILE_NAME": "unet_trt_exact16only_safe5_int8_20260704",
                "MUSETALK_TRT_STAGEWISE_WARMUP_BATCHES": "16",
                "HLS_SCHEDULER_MAX_BATCH": "16",
                "HLS_SCHEDULER_FIXED_BATCH_SIZES": "16",
                "MUSETALK_TRT_UNET_PATHS": "16:" + _relative(bs16_dir / "unet_trt.ts", root),
            }
        )
        notes.append(
            "selected: exact batch-16 only; avoids loading both UNet engines on 24GB GPUs"
        )
        return values, notes

    if bs8_valid:
        values.update(
            {
                "MUSETALK_TRT_PROFILE_NAME": "unet_trt_split8_safe5_int8_20260704",
                "MUSETALK_TRT_STAGEWISE_WARMUP_BATCHES": "8,16",
                "HLS_SCHEDULER_MAX_BATCH": "16",
                "HLS_SCHEDULER_FIXED_BATCH_SIZES": "8,16",
                "MUSETALK_TRT_UNET_PATHS": "8:" + _relative(bs8_dir / "unet_trt.ts", root),
            }
        )
        notes.append("selected: split batch-8 fallback")
        return values, notes

    raise SystemExit(
        "No validated UNet TRT artifact is available. "
        f"batch-16: {bs16_reason}; batch-8: {bs8_reason}"
    )


def parse_args() -> argparse.Namespace:
    root = _repo_root()
    parser = argparse.ArgumentParser(
        description="Write a runtime env file for the best validated MuseTalk TRT profile."
    )
    parser.add_argument("--repo-root", type=Path, default=root)
    parser.add_argument(
        "--output",
        type=Path,
        default=root / ".runtime" / "musetalk_trt_best.env",
    )
    parser.add_argument("--bs8-dir", default="models/tensorrt_unet_static_bs8_20260704")
    parser.add_argument("--bs16-dir", default="models/tensorrt_unet_static_bs16_20260704")
    parser.add_argument(
        "--prefer",
        choices=("exact16", "split8"),
        default="exact16",
        help="Prefer exact batch-16 when available; split8 remains the fallback.",
    )
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="Exit 0 and remove stale output when no validated artifact exists.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        values, notes = build_profile(args)
    except SystemExit:
        if not args.allow_missing:
            raise
        output = args.output if args.output.is_absolute() else args.repo_root / args.output
        if output.exists():
            output.unlink()
        print("No validated TRT profile available; continuing without generated profile")
        return 0

    output = args.output if args.output.is_absolute() else args.repo_root / args.output
    _write_env(output, values, notes)
    print(f"Wrote {output}")
    print(f"Selected {values['MUSETALK_TRT_PROFILE_NAME']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
